### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by missemily2022** [HuzunluArtemis/QMirrorLeechBot#8]
![image](https://user-images.githubusercontent.com/97376138/152109998-012eb31f-057d-4d74-945b-87648656315d.png)

Can these message be added?

**Comment by Vaibhav-08** [comment]
> Can these message be added?

I already gave you the idea and even gave you the script

**Comment by missemily2022** [comment]
@Vaibhav-08 Yeah bro I posted it before you gave me

**Comment by Vaibhav-08** [comment]
> @Vaibhav-08 Yeah bro I posted it before you gave me

Close your issue then

**Comment by nodirhajiev** [comment]
> > Can these message be added?
> 
> I already gave you the idea and even gave you the script

Hi. Could you give me the script like this?

**Comment by Vaibhav-08** [comment]
> > > Can these message be added?
> > 
> > 
> > I already gave you the idea and even gave you the script
> 
> Hi. Could you give me the script like this?

No
